### ISSUE TITLE
物品 - 壁挂饮水机的标题太长

### ISSUE THREAD

**Issue by TheHZDev** [VigtigsteL/AllInOneDeluxe2024#3]
在文件 `/data/language/base-language.txt` 中的第8336行

`壁挂饮水机\n\n需求：\n+ 饮水 20.00\n- 小便 7.00`

在游戏里这个物品的名称有4行，我想它原本应该只有前面的名称(`壁挂饮水机`)吧？

**Comment by VigtigsteL** [comment]
好的我今晚检查一下

**Comment by VigtigsteL** [comment]
已修复，感谢反馈。
